# Generated by Django 5.2.10 on 2026-01-27 18:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_userinteraction_timestamp_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userinteraction',
            name='unique_user_product_action',
        ),
        migrations.AddField(
            model_name='userinteraction',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='userinteraction',
            unique_together={('user', 'product')},
        ),
    ]
